- name: Install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: Start and enable
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Setting root password
  command: mysql_secure_installation --set-root-pass RoboShop@1
